#!/usr/bin/env bash
set -euo pipefail

# ============================================================

# get-stage1-values.sh

#

# Purpose:

# Print Stage 1 Terraform outputs required by Stage 2.

#

# Output is formatted as Terraform tfvars assignments,

# ready to copy and paste into terraform/02-ecs/terraform.tfvars.

#

# IMPORTANT:

# This script only reads Terraform outputs.

# It does NOT modify or overwrite terraform.tfvars.

#

# Usage from the ecs/ directory:

# ./get-stage1-values.sh

#

# Or specify the ecs/ project directory:

# ./get-stage1-values.sh /path/to/ecs

# ============================================================

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${1:-$SCRIPT_DIR}"
STAGE1_DIR="${PROJECT_DIR}/terraform/01-infrastructure"

# Check Terraform is installed.

if ! command -v terraform >/dev/null 2>&1; then
echo "ERROR: Terraform is not installed or not on PATH." >&2
exit 1
fi

# Check Stage 1 directory exists.

if [[ ! -d "$STAGE1_DIR" ]]; then
echo "ERROR: Stage 1 directory not found: $STAGE1_DIR" >&2
echo "Run this script from the ecs/ directory, or pass the ecs/ path as an argument." >&2
exit 1
fi

# Read Stage 1 outputs.

cd "$STAGE1_DIR"

outputs=(
vpc_id
public_subnet_a_id
public_subnet_b_id
ecr_frontend
ecr_backend
ecr_prometheus
ecr_grafana
db_endpoint
alb_dns_name
alb_security_group_id
frontend_target_group_arn
grafana_target_group_arn
prometheus_target_group_arn
)

# Read all outputs before printing, so a missing output does not

# leave you with a partially printed block to copy.

declare -A values

for name in "${outputs[@]}"; do
if ! value="$(terraform output -raw "$name" 2>/dev/null)"; then
echo "ERROR: Could not read Terraform output: $name" >&2
echo "Check available outputs with: terraform output" >&2
echo "Ensure Stage 1 has been applied and the output exists in outputs.tf." >&2
exit 1
fi

```
values["$name"]="$value"
```

done

# Print copy-and-paste-ready Terraform variables.

echo "# ============================================================"
echo "# Stage 1 outputs — paste into terraform/02-ecs/terraform.tfvars"
echo "# Generated by get-stage1-values.sh"
echo "# Existing variables and credentials should be kept."
echo "# ============================================================"
echo

for name in "${outputs[@]}"; do
printf '%-30s = "%s"\n' "$name" "${values[$name]}"
done

echo
echo "# End of Stage 1 values"
